/* Final fixes: exact Google Maps + TikTok placement + insurance logo visibility */
(() => {
  const MAPS_URL='https://goo.gl/maps/SvesNAt1qWMs38aP7';
  function styles(){if(document.getElementById('osaka-final-fix-style'))return;const s=document.createElement('style');s.id='osaka-final-fix-style';s.textContent=`.osaka-tiktok-link{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:8px!important;color:#fff!important;text-align:center!important;margin:20px auto!important;font-weight:800!important}.osaka-tiktok-icon{width:68px!important;height:68px!important;border-radius:16px!important;background:#fff!important;display:flex!important;align-items:center!important;justify-content:center!important;box-shadow:0 10px 28px rgba(0,0,0,.32)!important}.osaka-tiktok-icon svg{width:39px!important;height:39px!important}.osaka-tiktok-handle{font-size:15px!important;color:#fff!important}.insurance-panel-card .insurance-logo{opacity:1!important;visibility:visible!important;max-width:230px!important;height:92px!important;object-fit:contain!important}.insurance-panel-card.insurance-special-logo .insurance-logo{max-width:270px!important;height:108px!important}@media(max-width:800px){.insurance-panel-card .insurance-logo{max-width:175px!important;height:68px!important}.insurance-panel-card.insurance-special-logo .insurance-logo{max-width:205px!important;height:78px!important}}`;document.head.appendChild(s)}
  function tiktok(){const social=document.querySelector('.social');if(!social)return;const old=[...social.querySelectorAll('a')];const t=old.find(a=>/tiktok/i.test(a.textContent)||/@osakawindscreen/i.test(a.textContent));if(!t||t.classList.contains('osaka-tiktok-link'))return;const a=document.createElement('a');a.className='osaka-tiktok-link';a.href='https://www.tiktok.com/@osakawindscreen';a.target='_blank';a.rel='noopener noreferrer';a.innerHTML=`<span class="osaka-tiktok-icon" aria-label="TikTok official logo"><svg viewBox="0 0 48 48"><path fill="#111" d="M31.8 8.2c1.6 2.7 4.1 4.5 7.2 4.9v5.5c-2.9-.1-5.5-1-7.8-2.5v12.7c0 6.2-5 11.1-11.2 11.1-6.1 0-10.9-4.7-10.9-10.7 0-6.1 5-10.9 11.1-10.9.6 0 1.3.1 1.9.2v5.6c-.6-.2-1.2-.3-1.9-.3-3.1 0-5.6 2.4-5.6 5.4s2.4 5.3 5.4 5.3c3.1 0 5.7-2.5 5.7-5.7V8.2h6.1z"/></svg></span><span class="osaka-tiktok-handle">@osakawindscreen</span>`;t.replaceWith(a)}
  function maps(){document.querySelectorAll('a,button').forEach(el=>{const t=(el.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();if(!t)return;if(/google map location|google maps location|view more google rating|view more google reviews/.test(t)){if(el.tagName.toLowerCase()==='a'){el.href=MAPS_URL;el.target='_blank';el.rel='noopener noreferrer'}else{el.onclick=()=>window.open(MAPS_URL,'_blank','noopener,noreferrer')}el.dataset.osakaMapsFixed='1'}})}
  function insurance(){const map={lonpac:'ins-lonpac-logo.jpg',msig:'ins-msig-logo.png',progresif:'ins-progresif-logo.png',progressive:'ins-progresif-logo.png','tokio marine':'ins-tokio-logo.png',tokio:'ins-tokio-logo.png'};document.querySelectorAll('.insurance-panel-card').forEach(card=>{const strong=card.querySelector('strong');if(!strong)return;const text=strong.textContent.toLowerCase(),key=Object.keys(map).find(k=>text.includes(k));if(!key)return;card.classList.add('insurance-special-logo');let img=card.querySelector('.insurance-logo');if(!img){img=document.createElement('img');img.className='insurance-logo';card.appendChild(img)}img.alt=strong.textContent.trim()+' insurance logo';img.src='./'+map[key]+'?final=4'})}
  function init(){styles();tiktok();maps();insurance()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();setTimeout(init,700);setTimeout(init,1800);
})();
